spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Rute su navedene eksplicitno kako bi korisnicki zahtevi imali tacno
      # onaj oblik koji specifikacija zahteva.
      routes:
        # localhost:8765/currency-conversion?from=X&to=Y&quantity=Q
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion

        # localhost:8765/trade-service?from=X&to=Y&quantity=Q
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/trade-service

        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**

        - id: bank-account
          uri: lb://bank-account
          predicates:
            - Path=/bank-accounts/**

        - id: crypto-wallet
          uri: lb://crypto-wallet
          predicates:
            - Path=/crypto-wallets/**

        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**

        - id: crypto-exchange
          uri: lb://crypto-exchange
          predicates:
            - Path=/crypto-exchange/**

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.soas: INFO
    org.springframework.cloud.gateway: INFO
